# Generated by Django 4.1.3 on 2022-12-08 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_long', models.CharField(max_length=72)),
                ('weapon_type', models.CharField(choices=[('E', 'Epee'), ('F', 'Foil'), ('S', 'Sabre')], max_length=1)),
                ('is_wheelchair', models.BooleanField(default=False)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Mix')], max_length=1)),
                ('type', models.CharField(choices=[('I', 'Individual'), ('T', 'Team')], max_length=1)),
                ('age_group', models.CharField(max_length=64)),
                ('host_country', models.CharField(choices=[('HUN', 'Hungary'), ('ENG', 'England')], max_length=3)),
                ('address', models.CharField(max_length=128)),
                ('entry_fee', models.IntegerField()),
                ('currency', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FencerModel',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=72)),
                ('pre_nom', models.CharField(max_length=72)),
                ('sexe', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Mix')], max_length=1)),
                ('lateralite', models.CharField(choices=[('D', 'Droit'), ('G', 'Gauche')], max_length=1)),
                ('nation', models.CharField(choices=[('HUN', 'Hungary'), ('ENG', 'England')], max_length=3)),
                ('club', models.CharField(max_length=256)),
                ('licence', models.CharField(max_length=12)),
                ('statut', models.CharField(max_length=1)),
                ('date_naissance', models.DateField()),
                ('classement', models.IntegerField()),
                ('points', models.IntegerField()),
                ('barcode', models.IntegerField()),
                ('registration_status', models.BooleanField(default=False)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.competitionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_long', models.CharField(max_length=12)),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WeaponControlModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField()),
                ('assoc_competition_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.competitionmodel')),
                ('assoc_fencer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.fencermodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Fencer',
        ),
        migrations.AddField(
            model_name='competitionmodel',
            name='assoc_tournament_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tournamentmodel'),
        ),
    ]
