<<<<<<< HEAD
# Generated by Django 4.1.3 on 2023-01-02 14:12
=======
# Generated by Django 4.1.3 on 2022-12-21 20:49
>>>>>>> 444c236194bfa566cd13a452756b9f0a1d0357ed

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_fencermodel_competition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_13',
            field=models.SmallIntegerField(null=True, verbose_name='Length/ condition of body/ mask wire'),
        ),
    ]
