# Generated by Django 4.1.3 on 2022-12-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_weaponcontrolmodel_issue_13'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fencermodel',
            name='barcode',
            field=models.IntegerField(default='00000000'),
        ),
    ]
