# Generated by Django 4.1.3 on 2022-12-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_fencermodel_barcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionmodel',
            old_name='assoc_tournament_id',
            new_name='tournament',
        ),
        migrations.RenameField(
            model_name='weaponcontrolmodel',
            old_name='assoc_competition_id',
            new_name='competition',
        ),
        migrations.RenameField(
            model_name='weaponcontrolmodel',
            old_name='assoc_fencer_id',
            new_name='fencer',
        ),
    ]
