# Generated by Django 4.1.3 on 2023-01-02 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_rename_assoc_tournament_id_competitionmodel_tournament_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitionmodel',
            old_name='tournament',
            new_name='tournaments',
        ),
        migrations.RenameField(
            model_name='weaponcontrolmodel',
            old_name='competition',
            new_name='competitions',
        ),
        migrations.RenameField(
            model_name='weaponcontrolmodel',
            old_name='fencer',
            new_name='fencers',
        ),
    ]
