# Generated by Django 4.1.3 on 2023-01-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_tournament_competitionmodel_tournaments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionmodel',
            name='entry_fee',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fencermodel',
            name='points',
            field=models.FloatField(),
        ),
    ]
