# Generated by Django 4.1.3 on 2023-01-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_registrationmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fencermodel',
            name='registration_status',
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='registered',
            field=models.BooleanField(),
        ),
    ]
