# Generated by Django 4.1.3 on 2023-01-16 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_fencermodel_registration_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fencermodel',
            name='barcode',
        ),
    ]
