# Generated by Django 4.1.3 on 2023-04-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_weaponcontrolmodel_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='title_long',
            field=models.CharField(max_length=100),
        ),
    ]
