# Generated by Django 4.1.3 on 2023-04-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_alter_tournamentmodel_title_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_13',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Length / condition of body / mask wire'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_14',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Resistance of body / mask wire'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_17',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Mask: resistance (sabre / foil)'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_20',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Sabre / glove overlay condition'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_7',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Guard oxydation / deformation'),
        ),
    ]
