# Generated by Django 4.1.3 on 2023-04-25 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_alter_weaponcontrolmodel_issue_13_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PisteModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(choices=[('B', 'Blue'), ('Y', 'Yellow'), ('R', 'Red'), ('G', 'Green'), ('N', 'No color')], max_length=30)),
                ('is_active', models.BooleanField()),
                ('competitions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.competitionmodel')),
            ],
        ),
    ]
