# Generated by Django 4.1.3 on 2023-04-26 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_equipmentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualFormulaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_points', models.IntegerField()),
                ('table_points', models.IntegerField()),
                ('elimination_type', models.CharField(choices=[('DI', 'Direct elimination'), ('DO', 'Double elimination')], max_length=2)),
                ('separation_type', models.CharField(choices=[('N', 'Nation'), ('C', 'Club')], max_length=1)),
                ('direct_elimination_type', models.CharField(choices=[('O', 'One phase table'), ('T', 'Two phase table')], max_length=1)),
                ('third_place', models.BooleanField(default=False)),
                ('callroom', models.BooleanField(default=False)),
                ('callroom_number', models.IntegerField(choices=[(4, '4'), (8, '8'), (16, '16'), (32, '32'), (64, '64')], default=16)),
                ('competitions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.competitionmodel')),
            ],
        ),
    ]
