# Generated by Django 4.1.3 on 2023-05-17 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_individualformulamodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='weaponcontrolmodel',
            name='issue_29',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Weapon: Point weight'),
        ),
        migrations.AddField(
            model_name='weaponcontrolmodel',
            name='issue_30',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Weapon: Point gauge'),
        ),
        migrations.AddField(
            model_name='weaponcontrolmodel',
            name='issue_31',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Weapon: Bad guard condition'),
        ),
        migrations.AddField(
            model_name='weaponcontrolmodel',
            name='issue_32',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Weapon: Incorrect grip angle'),
        ),
        migrations.AddField(
            model_name='weaponcontrolmodel',
            name='issue_33',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Weapon: Missing insulation'),
        ),
        migrations.AddField(
            model_name='weaponcontrolmodel',
            name='issue_34',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Weapon: Missing pad'),
        ),
        migrations.AddField(
            model_name='weaponcontrolmodel',
            name='issue_35',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Other issue'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_1',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Jacket: Missing FIE mark'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_10',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Mask: Missing FIE mark'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_11',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Mask: Bad condition'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_12',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Mask: Incorrect printing'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_13',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Mask/overlay: High resistance'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_14',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Glove: Missing FIE mark'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_15',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Glove: Bad condition'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_16',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Glove/Overlay: Resistance'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_17',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Overlay: Condition'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_18',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Bodywire: Bad condition'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_19',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Bodywire: High resistance'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_2',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Jacket: Incorrent name printing'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_20',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Maskwire: Bad condition'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_21',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Maskwire: High resistance'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_22',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Weapon: Missing FIE mark'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_23',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Weapon: Too flexible blade'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_24',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Weapon: Too sharp blade'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_25',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Weapon: Blade too curved'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_26',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Weapon: Blade too long'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_27',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Weapon: Grip too long'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_28',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Weapon: Missing screw'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_3',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Breeches: Missing FIE mark'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_4',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Breeches: Incorrect logo printing'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_5',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Plastron: Missing FIE mark'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_6',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Plastron: Bad condition'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_7',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Electric jacket: Bad condition'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_8',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Electric jacket: Incorrect name printing'),
        ),
        migrations.AlterField(
            model_name='weaponcontrolmodel',
            name='issue_9',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Electric jacket: High resistance'),
        ),
    ]
