# Generated by Django 4.1.3 on 2023-05-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_weaponcontrolmodel_issue_29_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fencermodel',
            name='classement',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fencermodel',
            name='club',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='fencermodel',
            name='lateralite',
            field=models.CharField(choices=[('D', 'Droit'), ('G', 'Gauche')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='fencermodel',
            name='points',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fencermodel',
            name='statut',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
