import React from "react";
import { get } from '../../../services/backend.service';

export default function WCPrintHeader(props) {
  return (
    <div className="DocumentHeader DocumentColumnLayout">
      <div className="DocumentHeaderLeft">
        <div>
          <p className="DocumentHeaderTitle">WEAPON CONTROL</p>
          <p className="DocumentHeaderTitleExtension">STATISTICS</p>
          <p className="DocumentHeaderSubtitle">
            Generated by: <span>DARTGANAN</span>
          </p>
        </div>
      </div>
      <div className="DocumentHeaderMiddle">
        <b>{props.compTitle}</b>
        <p>{props.tourTitle}</p>
      </div>
      <div className="DocumentHeaderRight">
        <p>{props.sex}</p>
        <p>{props.compType}</p>
        <p>{props.ageGroup}</p>
        <p>{props.hostCountry}</p>
        <p>{props.year}</p>
      </div>
    </div>
  );
}
