#CHOICE OBJECTS FOR MODELS.PY
SEX_CHOICE = [
    ("M", "Male"),
    ("F", "Female"),
    ("X", "Mix"),
]
WEAPON_CHOICE = [
    ("E", "Epee"),
    ("F", "Foil"),
    ("S", "Sabre"),
]
LATERALITE_CHOICE = [
    ("D", "Droit"),
    ("G", "Gauche"),
]
NATION_CHOICE = [ 
    ("AFG", "Afghanistan"),
    ("ALA", "Åland Islands"),
    ("ALB", "Albania"),
    ("DZA", "Algeria"),
    ("ASM", "American Samoa"),
    ("AND", "Andorra"),
    ("AGO", "Angola"),
    ("AIA", "Anguilla"),
    ("ATA", "Antarctica"),
    ("ATG", "Antigua and Barbuda"),
    ("ARG", "Argentina"),
    ("ARM", "Armenia"),
    ("ABW", "Aruba"),
    ("AUS", "Australia"),
    ("AUT", "Austria"),
    ("AZE", "Azerbaijan"),
    ("BHS", "Bahamas"),
    ("BHR", "Bahrain"),
    ("BGD", "Bangladesh"),
    ("BRB", "Barbados"),
    ("BLR", "Belarus"),
    ("BEL", "Belgium"),
    ("BLZ", "Belize"),
    ("BEN", "Benin"),
    ("BMU", "Bermuda"),
    ("BTN", "Bhutan"),
    ("BOL", "Bolivia, Plurinational State of"),
    ("BES", "Bonaire, Sint Eustatius and Saba"),
    ("BIH", "Bosnia and Herzegovina"),
    ("BWA", "Botswana"),
    ("BVT", "Bouvet Island"),
    ("BRA", "Brazil"),
    ("IOT", "British Indian Ocean Territory"),
    ("BRN", "Brunei Darussalam"),
    ("BGR", "Bulgaria"),
    ("BFA", "Burkina Faso"),
    ("BDI", "Burundi"),
    ("KHM", "Cambodia"),
    ("CMR", "Cameroon"),
    ("CAN", "Canada"),
    ("CPV", "Cape Verde"),
    ("CYM", "Cayman Islands"),
    ("CAF", "Central African Republic"),
    ("TCD", "Chad"),
    ("CHL", "Chile"),
    ("CHN", "China"),
    ("CXR", "Christmas Island"),
    ("CCK", "Cocos (Keeling) Islands"),
    ("COL", "Colombia"),
    ("COM", "Comoros"),
    ("COG", "Congo"),
    ("COD", "Congo, the Democratic Republic of the"),
    ("COK", "Cook Islands"),
    ("CRI", "Costa Rica"),
    ("CIV", "Côte d'Ivoire"),
    ("HRV", "Croatia"),
    ("CUB", "Cuba"),
    ("CUW", "Curaçao"),
    ("CYP", "Cyprus"),
    ("CZE", "Czech Republic"),
    ("DNK", "Denmark"),
    ("DJI", "Djibouti"),
    ("DMA", "Dominica"),
    ("DOM", "Dominican Republic"),
    ("ECU", "Ecuador"),
    ("EGY", "Egypt"),
    ("SLV", "El Salvador"),
    ("GNQ", "Equatorial Guinea"),
    ("ERI", "Eritrea"),
    ("EST", "Estonia"),
    ("ETH", "Ethiopia"),
    ("FLK", "Falkland Islands (Malvinas)"),
    ("FRO", "Faroe Islands"),
    ("FJI", "Fiji"),
    ("FIN", "Finland"),
    ("FRA", "France"),
    ("GUF", "French Guiana"),
    ("PYF", "French Polynesia"),
    ("ATF", "French Southern Territories"),
    ("GAB", "Gabon"),
    ("GMB", "Gambia"),
    ("GEO", "Georgia"),
    ("DEU", "Germany"),
    ("GHA", "Ghana"),
    ("GIB", "Gibraltar"),
    ("GRC", "Greece"),
    ("GRL", "Greenland"),
    ("GRD", "Grenada"),
    ("GLP", "Guadeloupe"),
    ("GUM", "Guam"),
    ("GTM", "Guatemala"),
    ("GGY", "Guernsey"),
    ("GIN", "Guinea"),
    ("GNB", "Guinea-Bissau"),
    ("GUY", "Guyana"),
    ("HTI", "Haiti"),
    ("HMD", "Heard Island and McDonald Islands"),
    ("VAT", "Holy See (Vatican City State)"),
    ("HND", "Honduras"),
    ("HKG", "Hong Kong"),
    ("HUN", "Hungary"),
    ("ISL", "Iceland"),
    ("IND", "India"),
    ("IDN", "Indonesia"),
    ("IRN", "Iran, Islamic Republic of"),
    ("IRQ", "Iraq"),
    ("IRL", "Ireland"),
    ("IMN", "Isle of Man"),
    ("ISR", "Israel"),
    ("ITA", "Italy"),
    ("JAM", "Jamaica"),
    ("JPN", "Japan"),
    ("JEY", "Jersey"),
    ("JOR", "Jordan"),
    ("KAZ", "Kazakhstan"),
    ("KEN", "Kenya"),
    ("KIR", "Kiribati"),
    ("PRK", "Korea, Democratic People's Republic of"),
    ("KOR", "Korea, Republic of"),
    ("KWT", "Kuwait"),
    ("KGZ", "Kyrgyzstan"),
    ("LAO", "Lao People's Democratic Republic"),
    ("LVA", "Latvia"),
    ("LBN", "Lebanon"),
    ("LSO", "Lesotho"),
    ("LBR", "Liberia"),
    ("LBY", "Libya"),
    ("LIE", "Liechtenstein"),
    ("LTU", "Lithuania"),
    ("LUX", "Luxembourg"),
    ("MAC", "Macao"),
    ("MKD", "Macedonia, the former Yugoslav Republic of"),
    ("MDG", "Madagascar"),
    ("MWI", "Malawi"),
    ("MYS", "Malaysia"),
    ("MDV", "Maldives"),
    ("MLI", "Mali"),
    ("MLT", "Malta"),
    ("MHL", "Marshall Islands"),
    ("MTQ", "Martinique"),
    ("MRT", "Mauritania"),
    ("MUS", "Mauritius"),
    ("MYT", "Mayotte"),
    ("MEX", "Mexico"),
    ("FSM", "Micronesia, Federated States of"),
    ("MDA", "Moldova, Republic of"),
    ("MCO", "Monaco"),
    ("MNG", "Mongolia"),
    ("MNE", "Montenegro"),
    ("MSR", "Montserrat"),
    ("MAR", "Morocco"),
    ("MOZ", "Mozambique"),
    ("MMR", "Myanmar"),
    ("NAM", "Namibia"),
    ("NRU", "Nauru"),
    ("NPL", "Nepal"),
    ("NLD", "Netherlands"),
    ("NCL", "New Caledonia"),
    ("NZL", "New Zealand"),
    ("NIC", "Nicaragua"),
    ("NER", "Niger"),
    ("NGA", "Nigeria"),
    ("NIU", "Niue"),
    ("NFK", "Norfolk Island"),
    ("MNP", "Northern Mariana Islands"),
    ("NOR", "Norway"),
    ("OMN", "Oman"),
    ("PAK", "Pakistan"),
    ("PLW", "Palau"),
    ("PSE", "Palestinian Territory, Occupied"),
    ("PAN", "Panama"),
    ("PNG", "Papua New Guinea"),
    ("PRY", "Paraguay"),
    ("PER", "Peru"),
    ("PHL", "Philippines"),
    ("PCN", "Pitcairn"),
    ("POL", "Poland"),
    ("PRT", "Portugal"),
    ("PRI", "Puerto Rico"),
    ("QAT", "Qatar"),
    ("REU", "Réunion"),
    ("ROU", "Romania"),
    ("RUS", "Russian Federation"),
    ("RWA", "Rwanda"),
    ("BLM", "Saint Barthélemy"),
    ("SHN", "Saint Helena, Ascension and Tristan da Cunha"),
    ("KNA", "Saint Kitts and Nevis"),
    ("LCA", "Saint Lucia"),
    ("MAF", "Saint Martin (French part)"),
    ("SPM", "Saint Pierre and Miquelon"),
    ("VCT", "Saint Vincent and the Grenadines"),
    ("WSM", "Samoa"),
    ("SMR", "San Marino"),
    ("STP", "Sao Tome and Principe"),
    ("SAU", "Saudi Arabia"),
    ("SEN", "Senegal"),
    ("SRB", "Serbia"),
    ("SYC", "Seychelles"),
    ("SLE", "Sierra Leone"),
    ("SGP", "Singapore"),
    ("SXM", "Sint Maarten (Dutch part)"),
    ("SVK", "Slovakia"),
    ("SVN", "Slovenia"),
    ("SLB", "Solomon Islands"),
    ("SOM", "Somalia"),
    ("ZAF", "South Africa"),
    ("SGS", "South Georgia and the South Sandwich Islands"),
    ("SSD", "South Sudan"),
    ("ESP", "Spain"),
    ("LKA", "Sri Lanka"),
    ("SDN", "Sudan"),
    ("SUR", "Suriname"),
    ("SJM", "Svalbard and Jan Mayen"),
    ("SWZ", "Swaziland"),
    ("SWE", "Sweden"),
    ("CHE", "Switzerland"),
    ("SYR", "Syrian Arab Republic"),
    ("TWN", "Taiwan, Province of China"),
    ("TJK", "Tajikistan"),
    ("TZA", "Tanzania, United Republic of"),
    ("THA", "Thailand"),
    ("TLS", "Timor-Leste"),
    ("TGO", "Togo"),
    ("TKL", "Tokelau"),
    ("TON", "Tonga"),
    ("TTO", "Trinidad and Tobago"),
    ("TUN", "Tunisia"),
    ("TUR", "Turkey"),
    ("TKM", "Turkmenistan"),
    ("TCA", "Turks and Caicos Islands"),
    ("TUV", "Tuvalu"),
    ("UGA", "Uganda"),
    ("UKR", "Ukraine"),
    ("ARE", "United Arab Emirates"),
    ("GBR", "United Kingdom"),
    ("USA", "United States"),
    ("UMI", "United States Minor Outlying Islands"),
    ("URY", "Uruguay"),
    ("UZB", "Uzbekistan"),
    ("VUT", "Vanuatu"),
    ("VEN", "Venezuela, Bolivarian Republic of"),
    ("VNM", "Viet Nam"),
    ("VGB", "Virgin Islands, British"),
    ("VIR", "Virgin Islands, U.S."),
    ("WLF", "Wallis and Futuna"),
    ("ESH", "Western Sahara"),
    ("YEM", "Yemen"),
    ("ZMB", "Zambia"),
    ("ZWE", "Zimbabwe"),
]
COMPETITION_TYPE_CHOICE = [
    ("I", "Individual"),
    ("T", "Team"),
]
CURRENCY_CHOICE = [
    ("USD"), ("US Dollar"),
    ("CAD"), ("Canadian Dollar"),
    ("EUR"), ("Euro"),
    ("AED"), ("United Arab Emirates Dirham"),
    ("AFN"), ("Afghan Afghani"),
    ("ALL"), ("Albanian Lek"),
    ("AMD"), ("Armenian Dram"),
    ("ARS"), ("Argentine Peso"),
    ("AUD"), ("Australian Dollar"),
    ("AZN"), ("Azerbaijani Manat"),
    ("BAM"), ("Bosnia-Herzegovina Convertible Mark"),
    ("BDT"), ("Bangladeshi Taka"),
    ("BGN"), ("Bulgarian Lev"),
    ("BHD"), ("Bahraini Dinar"),
    ("BIF"), ("Burundian Franc"),
    ("BND"), ("Brunei Dollar"),
    ("BOB"), ("Bolivian Boliviano"),
    ("BRL"), ("Brazilian Real"),
    ("BWP"), ("Botswanan Pula"),
    ("BYN"), ("Belarusian Ruble"),
    ("BZD"), ("Belize Dollar"),
    ("CDF"), ("Congolese Franc"),
    ("CHF"), ("Swiss Franc"),
    ("CLP"), ("Chilean Peso"),
    ("CNY"), ("Chinese Yuan"),
    ("COP"), ("Colombian Peso"),
    ("CRC"), ("Costa Rican Colón"),
    ("CVE"), ("Cape Verdean Escudo"),
    ("CZK"), ("Czech Republic Koruna"),
    ("DJF"), ("Djiboutian Franc"),
    ("DKK"), ("Danish Krone"),
    ("DOP"), ("Dominican Peso"),
    ("DZD"), ("Algerian Dinar"),
    ("EEK"), ("Estonian Kroon"),
    ("EGP"), ("Egyptian Pound"),
    ("ERN"), ("Eritrean Nakfa"),
    ("ETB"), ("Ethiopian Birr"),
    ("GBP"), ("British Pound Sterling"),
    ("GEL"), ("Georgian Lari"),
    ("GHS"), ("Ghanaian Cedi"),
    ("GNF"), ("Guinean Franc"),
    ("GTQ"), ("Guatemalan Quetzal"),
    ("HKD"), ("Hong Kong Dollar"),
    ("HNL"), ("Honduran Lempira"),
    ("HRK"), ("Croatian Kuna"),
    ("HUF"), ("Hungarian Forint"),
    ("IDR"), ("Indonesian Rupiah"),
    ("ILS"), ("Israeli New Sheqel"),
    ("INR"), ("Indian Rupee"),
    ("IQD"), ("Iraqi Dinar"),
    ("IRR"), ("Iranian Rial"),
    ("ISK"), ("Icelandic Króna"),
    ("JMD"), ("Jamaican Dollar"),
    ("JOD"), ("Jordanian Dinar"),
    ("JPY"), ("Japanese Yen"),
    ("KES"), ("Kenyan Shilling"),
    ("KHR"), ("Cambodian Riel"),
    ("KMF"), ("Comorian Franc"),
    ("KRW"), ("South Korean Won"),
    ("KWD"), ("Kuwaiti Dinar"),
    ("KZT"), ("Kazakhstani Tenge"),
    ("LBP"), ("Lebanese Pound"),
    ("LKR"), ("Sri Lankan Rupee"),
    ("LTL"), ("Lithuanian Litas"),
    ("LVL"), ("Latvian Lats"),
    ("LYD"), ("Libyan Dinar"),
    ("MAD"), ("Moroccan Dirham"),
    ("MDL"), ("Moldovan Leu"),
    ("MGA"), ("Malagasy Ariary"),
    ("MKD"), ("Macedonian Denar"),
    ("MMK"), ("Myanma Kyat"),
    ("MOP"), ("Macanese Pataca"),
    ("MUR"), ("Mauritian Rupee"),
    ("MXN"), ("Mexican Peso"),
    ("MYR"), ("Malaysian Ringgit"),
    ("MZN"), ("Mozambican Metical"),
    ("NAD"), ("Namibian Dollar"),
    ("NGN"), ("Nigerian Naira"),
    ("NIO"), ("Nicaraguan Córdoba"),
    ("NOK"), ("Norwegian Krone"),
    ("NPR"), ("Nepalese Rupee"),
    ("NZD"), ("New Zealand Dollar"),
    ("OMR"), ("Omani Rial"),
    ("PAB"), ("Panamanian Balboa"),
    ("PEN"), ("Peruvian Nuevo Sol"),
    ("PHP"), ("Philippine Peso"),
    ("PKR"), ("Pakistani Rupee"),
    ("PLN"), ("Polish Zloty"),
    ("PYG"), ("Paraguayan Guarani"),
    ("QAR"), ("Qatari Rial"),
    ("RON"), ("Romanian Leu"),
    ("RSD"), ("Serbian Dinar"),
    ("RUB"), ("Russian Ruble"),
    ("RWF"), ("Rwandan Franc"),
    ("SAR"), ("Saudi Riyal"),
    ("SDG"), ("Sudanese Pound"),
    ("SEK"), ("Swedish Krona"),
    ("SGD"), ("Singapore Dollar"),
    ("SOS"), ("Somali Shilling"),
    ("SYP"), ("Syrian Pound"),
    ("THB"), ("Thai Baht"),
    ("TND"), ("Tunisian Dinar"),
    ("TOP"), ("Tongan Paʻanga"),
    ("TRY"), ("Turkish Lira"),
    ("TTD"), ("Trinidad and Tobago Dollar"),
    ("TWD"), ("New Taiwan Dollar"),
    ("TZS"), ("Tanzanian Shilling"),
    ("UAH"), ("Ukrainian Hryvnia"),
    ("UGX"), ("Ugandan Shilling"),
    ("UYU"), ("Uruguayan Peso"),
    ("UZS"), ("Uzbekistan Som"),
    ("VEF"), ("Venezuelan Bolívar"),
    ("VND"), ("Vietnamese Dong"),
    ("XAF"), ("CFA Franc BEAC"),
    ("XOF"), ("CFA Franc BCEAO"),
    ("YER"), ("Yemeni Rial"),
    ("ZAR"), ("South African Rand"),
    ("ZMK"), ("Zambian Kwacha"),
    ("ZWL"), ("Zimbabwean Dollar"),
]
