#CHOICE OBJECTS FOR MODELS.PY
SEX_CHOICE = [
    ("M", "Male"),
    ("F", "Female"),
    ("X", "Mix"),
]
WEAPON_CHOICE = [
    ("E", "Epee"),
    ("F", "Foil"),
    ("S", "Sabre"),
]
LATERALITE_CHOICE = [
    ("D", "Droit"),
    ("G", "Gauche"),
]
NATION_CHOICE = [
    ("AFG",	"Afghanistan"),
    ("ALB",	"Albania"),
    ("ALG",	"Algeria"),
    ("AND",	"Andorra"),
    ("ANG",	"Angola"),
    ("ANT",	"Antigua and Barbuda"),
    ("ARG",	"Argentina"),
    ("ARM",	"Armenia"),
    ("ARU",	"Aruba"),
    ("ASA",	"American Samoa"),
    ("AUS",	"Australia"),
    ("AUT",	"Austria"),
    ("AZE",	"Azerbaijan"),
    ("BAH",	"Bahamas"),
    ("BAN",	"Bangladesh"),
    ("BAR",	"Barbados"),
    ("BDI",	"Burundi"),
    ("BEL",	"Belgium"),
    ("BEN",	"Benin"),
    ("BER",	"Bermuda"),
    ("BHU",	"Bhutan"),
    ("BIH",	"Bosnia and Herzegovina"),
    ("BIZ",	"Belize"),
    ("BLR",	"Belarus"),
    ("BOL",	"Bolivia"),
    ("BOT",	"Botswana"),
    ("BRA",	"Brazil"),
    ("BRN",	"Bahrain"),
    ("BRU",	"Brunei"),
    ("BUL",	"Bulgaria"),
    ("BUR",	"Burkina Faso"),
    ("CAF",	"Central African Republic"),
    ("CAM",	"Cambodia"),
    ("CAN",	"Canada"),
    ("CAY",	"Cayman Islands"),
    ("CGO",	"Republic of the Congo"),
    ("CHA",	"Chad"),
    ("CHI",	"Chile"),
    ("CHN",	"China"),
    ("CIV",	"Ivory Coast"),
    ("CMR",	"Cameroon"),
    ("COD",	"Democratic Republic of the Congo"),
    ("COK",	"Cook Islands"),
    ("COL",	"Colombia"),
    ("COM",	"Comoros"),
    ("CPV",	"Cape Verde"),
    ("CRC",	"Costa Rica"),
    ("CRO",	"Croatia"),
    ("CUB",	"Cuba"),
    ("CYP",	"Cyprus"),
    ("CZE",	"Czechia"),
    ("DEN",	"Denmark"),
    ("DJI",	"Djibouti"),
    ("DMA",	"Dominica"),
    ("DOM",	"Dominican Republic"),
    ("ECU",	"Ecuador"),
    ("EGY",	"Egypt"),
    ("ERI",	"Eritrea"),
    ("ESA",	"El Salvador"),
    ("ESP",	"Spain"),
    ("EST",	"Estonia"),
    ("ETH",	"Ethiopia"),
    ("FIJ",	"Fiji"),
    ("FIN",	"Finland"),
    ("FRA",	"France"),
    ("FSM",	"Federated States of Micronesia"),
    ("GAB",	"Gabon"),
    ("GAM",	"The Gambia"),
    ("GBR",	"Great Britain"),
    ("GBS",	"Guinea-Bissau"),
    ("GEO",	"Georgia"),
    ("GEQ",	"Equatorial Guinea"),
    ("GER",	"Germany"),
    ("GHA",	"Ghana"),
    ("GRE",	"Greece"),
    ("GRN",	"Grenada"),
    ("GUA",	"Guatemala"),
    ("GUI",	"Guinea"),
    ("GUM",	"Guam"),
    ("GUY",	"Guyana"),
    ("HAI",	"Haiti"),
    ("HKG",	"Hong Kong, China"),
    ("HON",	"Honduras"),
    ("HUN",	"Hungary"),
    ("INA",	"Indonesia"),
    ("IND",	"India"),
    ("IRI",	"Iran"),
    ("IRL",	"Ireland"),
    ("IRQ",	"Iraq"),
    ("ISL",	"Iceland"),
    ("ISR",	"Israel"),
    ("ISV",	"Virgin Islands"),
    ("ITA",	"Italy"),
    ("IVB",	"British Virgin Islands"),
    ("JAM",	"Jamaica"),
    ("JOR",	"Jordan"),
    ("JPN",	"Japan"),
    ("KAZ",	"Kazakhstan"),
    ("KEN",	"Kenya"),
    ("KGZ",	"Kyrgyzstan"),
    ("KIR",	"Kiribati"),
    ("KOR",	"South Korea"),
    ("KOS",	"Kosovo"),
    ("KSA",	"Saudi Arabia"),
    ("KUW",	"Kuwait"),
    ("LAO",	"Laos"),
    ("LAT",	"Latvia"),
    ("LBA",	"Libya"),
    ("LBN",	"Lebanon"),
    ("LBR",	"Liberia"),
    ("LCA",	"Saint Lucia"),
    ("LES",	"Lesotho"),
    ("LIE",	"Liechtenstein"),
    ("LTU",	"Lithuania"),
    ("LUX",	"Luxembourg"),
    ("MAD",	"Madagascar"),
    ("MAR",	"Morocco"),
    ("MAS",	"Malaysia"),
    ("MAW",	"Malawi"),
    ("MDA",	"Moldova"),
    ("MDV",	"Maldives"),
    ("MEX",	"Mexico"),
    ("MGL",	"Mongolia"),
    ("MHL",	"Marshall Islands"),
    ("MKD",	"North Macedonia"),
    ("MLI",	"Mali"),
    ("MLT",	"Malta"),
    ("MNE",	"Montenegro"),
    ("MON",	"Monaco"),
    ("MOZ",	"Mozambique"),
    ("MRI",	"Mauritius"),
    ("MTN",	"Mauritania"),
    ("MYA",	"Myanmar"),
    ("NAM",	"Namibia"),
    ("NCA",	"Nicaragua"),
    ("NED",	"Netherlands"),
    ("NEP",	"Nepal"),
    ("NGR",	"Nigeria"),
    ("NIG",	"Niger"),
    ("NOR",	"Norway"),
    ("NRU",	"Nauru"),
    ("NZL",	"New Zealand"),
    ("OMA",	"Oman"),
    ("PAK",	"Pakistan"),
    ("PAN",	"Panama"),
    ("PAR",	"Paraguay"),
    ("PER",	"Peru"),
    ("PHI",	"Philippines"),
    ("PLE",	"Palestine"),
    ("PLW",	"Palau"),
    ("PNG",	"Papua New Guinea"),
    ("POL",	"Poland"),
    ("POR",	"Portugal"),
    ("PRK",	"North Korea"),
    ("PUR",	"Puerto Rico"),
    ("QAT",	"Qatar"),
    ("ROU",	"Romania"),
    ("RSA",	"South Africa"),
    ("RUS",	"Russia"),
    ("RWA",	"Rwanda"),
    ("SAM",	"Samoa"),
    ("SEN",	"Senegal"),
    ("SEY",	"Seychelles"),
    ("SGP",	"Singapore"),
    ("SKN",	"Saint Kitts and Nevis"),
    ("SLE",	"Sierra Leone"),
    ("SLO",	"Slovenia"),
    ("SMR",	"San Marino"),
    ("SOL",	"Solomon Islands"),
    ("SOM",	"Somalia"),
    ("SRB",	"Serbia"),
    ("SRI",	"Sri Lanka"),
    ("SSD",	"South Sudan"),
    ("STP",	"Sao Tome and Principe"),
    ("SUD",	"Sudan"),
    ("SUI",	"Switzerland"),
    ("SUR",	"Suriname"),
    ("SVK",	"Slovakia"),
    ("SWE",	"Sweden"),
    ("SWZ",	"Eswatini"),
    ("SYR",	"Syria"),
    ("TAN",	"Tanzania"),
    ("TGA",	"Tonga"),
    ("THA",	"Thailand"),
    ("TJK",	"Tajikistan"),
    ("TKM",	"Turkmenistan"),
    ("TLS",	"East Timor"),
    ("TOG",	"Togo"),
    ("TPE",	"Chinese Taipei"),
    ("TTO",	"Trinidad and Tobago"),
    ("TUN",	"Tunisia"),
    ("TUR",	"Turkey"),
    ("TUV",	"Tuvalu"),
    ("UAE",	"United Arab Emirates"),
    ("UGA",	"Uganda"),
    ("UKR",	"Ukraine"),
    ("URU",	"Uruguay"),
    ("USA",	"United States"),
    ("UZB",	"Uzbekistan"),
    ("VAN",	"Vanuatu"),
    ("VEN",	"Venezuela"),
    ("VIE",	"Vietnam"),
    ("VIN",	"Saint Vincent and the Grenadines"),
    ("YEM",	"Yemen"),
    ("ZAM", "Zambia"),
    ("ZIM",	"Zimbabwe"),
]
COMPETITION_TYPE_CHOICE = [
    ("I", "Individual"),
    ("T", "Team"),
]
CURRENCY_CHOICE = [
    ("USD"), ("US Dollar"),
    ("CAD"), ("Canadian Dollar"),
    ("EUR"), ("Euro"),
    ("AED"), ("United Arab Emirates Dirham"),
    ("AFN"), ("Afghan Afghani"),
    ("ALL"), ("Albanian Lek"),
    ("AMD"), ("Armenian Dram"),
    ("ARS"), ("Argentine Peso"),
    ("AUD"), ("Australian Dollar"),
    ("AZN"), ("Azerbaijani Manat"),
    ("BAM"), ("Bosnia-Herzegovina Convertible Mark"),
    ("BDT"), ("Bangladeshi Taka"),
    ("BGN"), ("Bulgarian Lev"),
    ("BHD"), ("Bahraini Dinar"),
    ("BIF"), ("Burundian Franc"),
    ("BND"), ("Brunei Dollar"),
    ("BOB"), ("Bolivian Boliviano"),
    ("BRL"), ("Brazilian Real"),
    ("BWP"), ("Botswanan Pula"),
    ("BYN"), ("Belarusian Ruble"),
    ("BZD"), ("Belize Dollar"),
    ("CDF"), ("Congolese Franc"),
    ("CHF"), ("Swiss Franc"),
    ("CLP"), ("Chilean Peso"),
    ("CNY"), ("Chinese Yuan"),
    ("COP"), ("Colombian Peso"),
    ("CRC"), ("Costa Rican Colón"),
    ("CVE"), ("Cape Verdean Escudo"),
    ("CZK"), ("Czech Republic Koruna"),
    ("DJF"), ("Djiboutian Franc"),
    ("DKK"), ("Danish Krone"),
    ("DOP"), ("Dominican Peso"),
    ("DZD"), ("Algerian Dinar"),
    ("EEK"), ("Estonian Kroon"),
    ("EGP"), ("Egyptian Pound"),
    ("ERN"), ("Eritrean Nakfa"),
    ("ETB"), ("Ethiopian Birr"),
    ("GBP"), ("British Pound Sterling"),
    ("GEL"), ("Georgian Lari"),
    ("GHS"), ("Ghanaian Cedi"),
    ("GNF"), ("Guinean Franc"),
    ("GTQ"), ("Guatemalan Quetzal"),
    ("HKD"), ("Hong Kong Dollar"),
    ("HNL"), ("Honduran Lempira"),
    ("HRK"), ("Croatian Kuna"),
    ("HUF"), ("Hungarian Forint"),
    ("IDR"), ("Indonesian Rupiah"),
    ("ILS"), ("Israeli New Sheqel"),
    ("INR"), ("Indian Rupee"),
    ("IQD"), ("Iraqi Dinar"),
    ("IRR"), ("Iranian Rial"),
    ("ISK"), ("Icelandic Króna"),
    ("JMD"), ("Jamaican Dollar"),
    ("JOD"), ("Jordanian Dinar"),
    ("JPY"), ("Japanese Yen"),
    ("KES"), ("Kenyan Shilling"),
    ("KHR"), ("Cambodian Riel"),
    ("KMF"), ("Comorian Franc"),
    ("KRW"), ("South Korean Won"),
    ("KWD"), ("Kuwaiti Dinar"),
    ("KZT"), ("Kazakhstani Tenge"),
    ("LBP"), ("Lebanese Pound"),
    ("LKR"), ("Sri Lankan Rupee"),
    ("LTL"), ("Lithuanian Litas"),
    ("LVL"), ("Latvian Lats"),
    ("LYD"), ("Libyan Dinar"),
    ("MAD"), ("Moroccan Dirham"),
    ("MDL"), ("Moldovan Leu"),
    ("MGA"), ("Malagasy Ariary"),
    ("MKD"), ("Macedonian Denar"),
    ("MMK"), ("Myanma Kyat"),
    ("MOP"), ("Macanese Pataca"),
    ("MUR"), ("Mauritian Rupee"),
    ("MXN"), ("Mexican Peso"),
    ("MYR"), ("Malaysian Ringgit"),
    ("MZN"), ("Mozambican Metical"),
    ("NAD"), ("Namibian Dollar"),
    ("NGN"), ("Nigerian Naira"),
    ("NIO"), ("Nicaraguan Córdoba"),
    ("NOK"), ("Norwegian Krone"),
    ("NPR"), ("Nepalese Rupee"),
    ("NZD"), ("New Zealand Dollar"),
    ("OMR"), ("Omani Rial"),
    ("PAB"), ("Panamanian Balboa"),
    ("PEN"), ("Peruvian Nuevo Sol"),
    ("PHP"), ("Philippine Peso"),
    ("PKR"), ("Pakistani Rupee"),
    ("PLN"), ("Polish Zloty"),
    ("PYG"), ("Paraguayan Guarani"),
    ("QAR"), ("Qatari Rial"),
    ("RON"), ("Romanian Leu"),
    ("RSD"), ("Serbian Dinar"),
    ("RUB"), ("Russian Ruble"),
    ("RWF"), ("Rwandan Franc"),
    ("SAR"), ("Saudi Riyal"),
    ("SDG"), ("Sudanese Pound"),
    ("SEK"), ("Swedish Krona"),
    ("SGD"), ("Singapore Dollar"),
    ("SOS"), ("Somali Shilling"),
    ("SYP"), ("Syrian Pound"),
    ("THB"), ("Thai Baht"),
    ("TND"), ("Tunisian Dinar"),
    ("TOP"), ("Tongan Paʻanga"),
    ("TRY"), ("Turkish Lira"),
    ("TTD"), ("Trinidad and Tobago Dollar"),
    ("TWD"), ("New Taiwan Dollar"),
    ("TZS"), ("Tanzanian Shilling"),
    ("UAH"), ("Ukrainian Hryvnia"),
    ("UGX"), ("Ugandan Shilling"),
    ("UYU"), ("Uruguayan Peso"),
    ("UZS"), ("Uzbekistan Som"),
    ("VEF"), ("Venezuelan Bolívar"),
    ("VND"), ("Vietnamese Dong"),
    ("XAF"), ("CFA Franc BEAC"),
    ("XOF"), ("CFA Franc BCEAO"),
    ("YER"), ("Yemeni Rial"),
    ("ZAR"), ("South African Rand"),
    ("ZMK"), ("Zambian Kwacha"),
    ("ZWL"), ("Zimbabwean Dollar"),
]
PISTE_COLOR_CHOICE = [
    ("B", "Blue"),
    ("Y", "Yellow"),
    ("R", "Red"),
    ("G", "Green"),
    ("N", "No color")
]
ELIMINATION_TYPE_CHOICE = [ 
    ("DI", "Direct elimination"),
    ("DO", "Double elimination")
]

SEPARATION_TYPE_CHOICE = [ 
    ("N", "Nation"),
    ("C", "Club")
]
DIRECT_ELIMINATION_TYPE_CHOICE = [
    ("O", "One phase table"), 
    ("T", "Two phase table")
]
CALLROOM_NUMBER_CHOICE = [
   (4, "4"),
   (8, "8"),
   (16, "16"),
   (32, "32"),
   (64, "64")
]
