issues_list = { 
      "issue_1" : "Jacket: Missing FIE mark",
      "issue_2" : "Jacket: Incorrent name printing",
      "issue_3" : "Breeches: Missing FIE mark",
      "issue_4" : "Breeches: Incorrect logo printing",
      "issue_5" : "Plastron: Missing FIE mark",
      "issue_6" : "Plastron: Bad condition",
      "issue_7" : "Electric jacket: Bad condition",
      "issue_8" : "Electric jacket: Incorrect name printing",
      "issue_9" : "Electric jacket: High resistance",
      "issue_10" : "Mask: Missing FIE mark",
      "issue_11" : "Mask: Bad condition",
      "issue_12" : "Mask: Incorrect printing",
      "issue_13" : "Mask/overlay: High resistance",
      "issue_14" : "Glove: Missing FIE mark",
      "issue_15" : "Glove: Bad condition",
      "issue_16" : "Glove/Overlay: Resistance",
      "issue_17" : "Overlay: Condition",
      "issue_18" : "Bodywire: Bad condition",
      "issue_19" : "Bodywire: High resistance",
      "issue_20" : "Maskwire: Bad condition",
      "issue_21" : "Maskwire: High resistance",
      "issue_22" : "Weapon: Missing FIE mark",
      "issue_23" : "Weapon: Too flexible blade",
      "issue_24" : "Weapon: Too sharp blade",
      "issue_25" : "Weapon: Blade too curved",
      "issue_26" : "Weapon: Blade too long",
      "issue_27" : "Weapon: Grip too long",
      "issue_28" : "Weapon: Missing screw",
      "issue_29" : "Weapon: Point weight",
      "issue_30" : "Weapon: Point gauge",
      "issue_31" : "Weapon: Bad guard condition",
      "issue_32" : "Weapon: Incorrect grip angle",
      "issue_33" : "Weapon: Missing insulation",
      "issue_34" : "Weapon: Missing pad",
      "issue_35" : "Other issue",
}
