issues_list = { 
   "issue_1": "FIE mark on blade",
   "issue_2": "Arm gap and weight",
   "issue_3": "Arm length",
   "issue_4": "Blade length",
   "issue_5": "Grip length",
   "issue_6": "Form and depth of the guard",
   "issue_7": "Guard oxydation/ deformation",
   "issue_8": "Excentricity of the blade",
   "issue_9": "Blade flexibility",
   "issue_10": "Curve on the blade",
   "issue_11": "Foucault current device",
   "issue_12": "Point and arm size",
   "issue_13": "Length/ condition of body/ mask wire",
   "issue_14": "Resistance of body/ mask wire",
   "issue_15": "Mask: FIE mark",
   "issue_16": "Mask: condition and insulation",
   "issue_17": "Mask: resistance (sabre/foil",
   "issue_18": "Metallic jacket condition",
   "issue_19": "Metallic jacket resistance",
   "issue_20": "Sabre/ glove overlay condition",
   "issue_21": "Sabre glove overlay resistance",
   "issue_22": "Glove condition",
   "issue_23": "Foil chest protector",
   "issue_24": "Socks",
   "issue_25": "Incorrect name printing",
   "issue_26": "Incorrect national logo",
   "issue_27": "Commercial",
   "issue_28": "Other items",
}
